name: SecureRISC CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  simulation:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Icarus Verilog
        run: |
          sudo apt-get update
          sudo apt-get install -y iverilog

      - name: Compile CPU
        run: |
          iverilog -g2012 \
          -o cpu_sim \
          rtl/secure_risc_core.v \
          rtl/alu_v2.v \
          rtl/register_file.v \
          rtl/program_counter.v \
          rtl/instruction_decoder.v \
          rtl/immediate_generator.v \
          rtl/instruction_memory.v \
          rtl/data_memory.v \
          rtl/instruction_verifier.v \
          rtl/memory_protection_unit.v \
          testbench/secure_risc_core_tb.v

      - name: Run CPU test
        run: vvp cpu_sim

      - name: Compile Instruction Verifier
        run: |
          iverilog -g2012 \
          -o verifier_sim \
          rtl/instruction_verifier.v \
          testbench/instruction_verifier_tb.v

      - name: Run Instruction Verifier
        run: vvp verifier_sim
